# -*- coding: utf-8 -*-
"""Twitter Analysis 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10UImuTn-3j1YaGsPSMMP6p4gJasU2ezs
"""

import numpy as np
import pandas as pd

train_data = pd.read_csv('train.csv')
test_data = pd.read_csv('test.csv')
train_data = train_data.drop('id',axis=1)

import seaborn as sns
sns.countplot(train_data['label'])

size = train_data.shape[0]
print(size)

import nltk
import re
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

def prepare_corpus(tweets):
  corpus_tweets = []
  size = tweets.shape[0]
  ps = PorterStemmer()
  for i in range(0,size):
    tweet = re.sub(pattern='[^a-zA-Z]',repl=' ', string=tweets['tweet'][i])

    tweet = re.sub(pattern='user' , repl='' , string = tweet)

    tweet = tweet.lower()

    words = tweet.split()

    words = [ps.stem(word) for word in words if not word in stopwords.words('english')]

    tweet = ' '.join(words)

    corpus_tweets.append(tweet)
  return corpus_tweets

corpus_tweets_train = prepare_corpus(train_data)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000)
X_cv = cv.fit_transform(corpus_tweets_train).toarray()
y_cv = train_data['label'].values

from sklearn.model_selection import train_test_split
def split_train_test(X,y):
  X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.10)
  return X_train , X_test , y_train , y_test

X_train_cv , X_test_cv , y_train_cv , y_test_cv = split_train_test(X_cv , y_cv)

from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
def accuracy_check(model,data,label):
  y_pred = model.predict(data)
  print(classification_report(label , y_pred)) 
  accuracy = accuracy_score(label , y_pred)
  return accuracy

from sklearn.naive_bayes import MultinomialNB
nb_cv=MultinomialNB()

nb_cv.fit(X_train_cv , y_train_cv)
nb_cv_accuracy = accuracy_check(nb_cv , X_test_cv , y_test_cv)
print(nb_cv_accuracy)

